version: "3.8"
services:
  db:
    image: mysql:8.0.26
    container_name: todo_db_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: takumi
      MYSQL_PASSWORD: seacret
      TZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3308:3306
volumes:
  db_data:
